---

- name: Check if the files already exists
  stat:
    path: "{{ dataset_folder_path }}/{{ item.filename }}"
    get_checksum: False
    get_md5: False
  register: downloaded_file_status

#- name: Download into dataset folder
#  get_url:
#    url: "{{ item.url }}"
#    dest: "{{ dataset_folder_path }}/{{ item.filename }}"
#    mode: 0755
#    timeout: "{{ item.timeout | default(200) }}"
#  retries: 3
#  register: item_result
#  when: downloaded_file_status.stat.exists == false

- name: Download file
  command: "{{ ansible_python_interpreter }} {{ script_folder }}/download_script.py {{ script_folder }}/credentials.json {{ script_folder }}/token.json {{ dataset_folder_path }}/{{ item.filename }} {{ item.google_file_id }}"
  args:
    creates: "{{ dataset_folder_path }}/{{ item.filename }}"
  become: yes
  become_method: sudo
  retries: 3
  register: item_result
  when: downloaded_file_status.stat.exists == false

- name: Check if the file is downloaded
  stat:
    path: "{{ dataset_folder_path }}/{{ item.filename }}"
    get_checksum: False
    get_md5: False
  register: downloaded_file_status

#- name: Check if file has pre-made checksum file
#  stat:
#    path: "{{ item.filename }}.sha1sum"
#  register: checksum_file
#  when: downloaded_file_status.stat.exists == true
#
#- name: Synchronise checksum file to location
#  synchronize:
#      src: "{{ item.filename }}.sha1sum"
#      dest: "{{ dataset_folder_path }}/{{ item.filename }}.sha1sum"
#  when: checksum_file.stat.exists == false and downloaded_file_status.stat.exists == true

- name: Check if file has checksum file
  stat:
    path: "{{ dataset_folder_path }}/{{ item.filename }}.sha1sum"
    get_checksum: False
    get_md5: False
  register: checksum_file
  when: downloaded_file_status.stat.exists == true

- name: Delete check sum file if file does not exist
  file:
    path: "{{ dataset_folder_path }}/{{ item.filename }}.sha1sum"
    state: absent
  when: downloaded_file_status.stat.exists == false

- name: Calculate Checksum if checksum file does not exist and file does exist
  shell: "shasum -a 1 {{ dataset_folder_path }}/{{ item.filename }}"
  register: checksum
  when: downloaded_file_status.stat.exists == true and checksum_file is defined and checksum_file.stat.exists == false

- name: Create checksum of file and put in checksum value
  copy:
    content: "{{ checksum.stdout }}"
    dest: "{{ dataset_folder_path }}/{{ item.filename }}.sha1sum"
  when: downloaded_file_status.stat.exists == true and checksum_file is defined and checksum_file.stat.exists == false

- name: Read checksum file
  shell: "cat {{ dataset_folder_path }}/{{ item.filename }}.sha1sum"
  register: checksum
  when: downloaded_file_status.stat.exists == true

- name: Check checksums are equal by reading checksum file
  assert:
    that: "{{ checksum.stdout.find(item.sha1sum) != -1 }}"
    fail_msg: "Checksum does not match for file {{ item.filename }}. Expected {{ item.sha1sum }}. Got {{ checksum.stdout }}"
    success_msg: "Checksum matches for file {{ item.filename }}."
  register: checksum_assert
  when: downloaded_file_status.stat.exists == true

...