---

- name: Create workspace
  file:
    path: "{{ workspace_dir }}"
    state: directory
    mode: "0755"

- name: Update pip
  pip:
    name: pip
    state: latest

#- name: Install tmux
#  package:
#    name: tmux
#    state: present

#- name: Install virtual env
#  pip:
#    name: virtualenv
#    state: present

#- name: Permissions for virtual env activate
#  file:
#    path: "{{ virtual_env_activate }}"
#    state: file
#    mode: "0755"
#  become: yes
#  become_method: sudo

#- name: Install modules for download script
#  pip:
#    name:
#      - google-auth-oauthlib
#      - google-api-python-client
#      - google-auth-httplib2
#    state: present

- name: Set environment variable for the dataset directory path
  lineinfile:
      dest: ~/.bashrc
      line: 'export DATASET_DIR="{{ dataset_folder_path }}"'

...